<?php

namespace Database\Seeders;

use App\Models\Pharmacy;
use Illuminate\Database\Seeder;

class PharmacySeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'category' => 'Pain Reliever',
                'description' => 'For pain and fever relief',
                'price' => 5.99,
                'stock_quantity' => 100,
                'manufacturer' => 'Generic Pharma',
                'expiry_date' => '2025-12-31',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'category' => 'Antibiotic',
                'description' => 'Antibiotic for bacterial infections',
                'price' => 15.99,
                'stock_quantity' => 50,
                'manufacturer' => 'Medical Labs',
                'expiry_date' => '2025-06-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'category' => 'Antacid',
                'description' => 'For acid reflux and ulcers',
                'price' => 12.99,
                'stock_quantity' => 75,
                'manufacturer' => 'Health Pharma',
                'expiry_date' => '2025-09-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'category' => 'Blood Pressure',
                'description' => 'For high blood pressure',
                'price' => 25.99,
                'stock_quantity' => 60,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-08-31',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Metformin',
                'generic_name' => 'Metformin HCl',
                'category' => 'Diabetes',
                'description' => 'For type 2 diabetes',
                'price' => 18.99,
                'stock_quantity' => 80,
                'manufacturer' => 'DiabeCare',
                'expiry_date' => '2025-07-31',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'category' => 'Pain Reliever',
                'description' => 'Anti-inflammatory pain reliever',
                'price' => 7.99,
                'stock_quantity' => 120,
                'manufacturer' => 'PainFree',
                'expiry_date' => '2025-11-30',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Cetirizine',
                'generic_name' => 'Cetirizine HCl',
                'category' => 'Antihistamine',
                'description' => 'For allergies',
                'price' => 9.99,
                'stock_quantity' => 90,
                'manufacturer' => 'AllergyMed',
                'expiry_date' => '2025-10-31',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Sertraline',
                'generic_name' => 'Sertraline HCl',
                'category' => 'Antidepressant',
                'description' => 'For depression and anxiety',
                'price' => 35.99,
                'stock_quantity' => 40,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-05-31',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Amlodipine',
                'generic_name' => 'Amlodipine Besylate',
                'category' => 'Blood Pressure',
                'description' => 'Calcium channel blocker',
                'price' => 22.99,
                'stock_quantity' => 70,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-08-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Levothyroxine',
                'generic_name' => 'Levothyroxine Sodium',
                'category' => 'Thyroid',
                'description' => 'For thyroid hormone replacement',
                'price' => 28.99,
                'stock_quantity' => 55,
                'manufacturer' => 'ThyroidCare',
                'expiry_date' => '2025-07-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'category' => 'Pain Reliever',
                'description' => 'Pain relief and blood thinner',
                'price' => 6.99,
                'stock_quantity' => 150,
                'manufacturer' => 'HeartCare',
                'expiry_date' => '2025-12-15',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Loratadine',
                'generic_name' => 'Loratadine',
                'category' => 'Antihistamine',
                'description' => 'For allergies and hay fever',
                'price' => 8.99,
                'stock_quantity' => 85,
                'manufacturer' => 'AllergyMed',
                'expiry_date' => '2025-09-15',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Pantoprazole',
                'generic_name' => 'Pantoprazole Sodium',
                'category' => 'Antacid',
                'description' => 'For acid reflux and GERD',
                'price' => 19.99,
                'stock_quantity' => 65,
                'manufacturer' => 'GastroHealth',
                'expiry_date' => '2025-08-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Metoprolol',
                'generic_name' => 'Metoprolol Tartrate',
                'category' => 'Beta Blocker',
                'description' => 'For high blood pressure and angina',
                'price' => 24.99,
                'stock_quantity' => 45,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-06-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Escitalopram',
                'generic_name' => 'Escitalopram Oxalate',
                'category' => 'Antidepressant',
                'description' => 'For depression and anxiety',
                'price' => 32.99,
                'stock_quantity' => 35,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-07-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Montelukast',
                'generic_name' => 'Montelukast Sodium',
                'category' => 'Asthma',
                'description' => 'For asthma and allergies',
                'price' => 45.99,
                'stock_quantity' => 30,
                'manufacturer' => 'RespiCare',
                'expiry_date' => '2025-05-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Gabapentin',
                'generic_name' => 'Gabapentin',
                'category' => 'Anticonvulsant',
                'description' => 'For nerve pain and epilepsy',
                'price' => 29.99,
                'stock_quantity' => 40,
                'manufacturer' => 'NeuroCare',
                'expiry_date' => '2025-08-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Fluoxetine',
                'generic_name' => 'Fluoxetine HCl',
                'category' => 'Antidepressant',
                'description' => 'For depression and OCD',
                'price' => 27.99,
                'stock_quantity' => 50,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-09-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Losartan',
                'generic_name' => 'Losartan Potassium',
                'category' => 'Blood Pressure',
                'description' => 'For high blood pressure',
                'price' => 26.99,
                'stock_quantity' => 55,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-10-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Atorvastatin',
                'generic_name' => 'Atorvastatin Calcium',
                'category' => 'Cholesterol',
                'description' => 'For high cholesterol',
                'price' => 38.99,
                'stock_quantity' => 45,
                'manufacturer' => 'HeartCare',
                'expiry_date' => '2025-11-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Ranitidine',
                'generic_name' => 'Ranitidine HCl',
                'category' => 'Antacid',
                'description' => 'For heartburn and ulcers',
                'price' => 16.99,
                'stock_quantity' => 70,
                'manufacturer' => 'GastroHealth',
                'expiry_date' => '2025-12-25',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Tramadol',
                'generic_name' => 'Tramadol HCl',
                'category' => 'Pain Reliever',
                'description' => 'For moderate to severe pain',
                'price' => 42.99,
                'stock_quantity' => 35,
                'manufacturer' => 'PainFree',
                'expiry_date' => '2025-06-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Citalopram',
                'generic_name' => 'Citalopram HBr',
                'category' => 'Antidepressant',
                'description' => 'For depression',
                'price' => 31.99,
                'stock_quantity' => 45,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-07-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Albuterol',
                'generic_name' => 'Albuterol Sulfate',
                'category' => 'Bronchodilator',
                'description' => 'For asthma and COPD',
                'price' => 48.99,
                'stock_quantity' => 40,
                'manufacturer' => 'RespiCare',
                'expiry_date' => '2025-08-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Duloxetine',
                'generic_name' => 'Duloxetine HCl',
                'category' => 'Antidepressant',
                'description' => 'For depression and anxiety',
                'price' => 44.99,
                'stock_quantity' => 35,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-09-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Warfarin',
                'generic_name' => 'Warfarin Sodium',
                'category' => 'Anticoagulant',
                'description' => 'Blood thinner',
                'price' => 36.99,
                'stock_quantity' => 30,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-10-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Furosemide',
                'generic_name' => 'Furosemide',
                'category' => 'Diuretic',
                'description' => 'For fluid retention',
                'price' => 21.99,
                'stock_quantity' => 50,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-11-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Clonazepam',
                'generic_name' => 'Clonazepam',
                'category' => 'Anticonvulsant',
                'description' => 'For seizures and panic disorder',
                'price' => 39.99,
                'stock_quantity' => 25,
                'manufacturer' => 'NeuroCare',
                'expiry_date' => '2025-12-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Venlafaxine',
                'generic_name' => 'Venlafaxine HCl',
                'category' => 'Antidepressant',
                'description' => 'For depression and anxiety',
                'price' => 37.99,
                'stock_quantity' => 40,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-06-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Carvedilol',
                'generic_name' => 'Carvedilol',
                'category' => 'Beta Blocker',
                'description' => 'For heart failure and blood pressure',
                'price' => 33.99,
                'stock_quantity' => 45,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-07-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Hydroxyzine',
                'generic_name' => 'Hydroxyzine HCl',
                'category' => 'Antihistamine',
                'description' => 'For anxiety and allergies',
                'price' => 23.99,
                'stock_quantity' => 55,
                'manufacturer' => 'AllergyMed',
                'expiry_date' => '2025-08-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Meloxicam',
                'generic_name' => 'Meloxicam',
                'category' => 'Anti-inflammatory',
                'description' => 'For arthritis pain',
                'price' => 28.99,
                'stock_quantity' => 50,
                'manufacturer' => 'PainFree',
                'expiry_date' => '2025-09-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Cyclobenzaprine',
                'generic_name' => 'Cyclobenzaprine HCl',
                'category' => 'Muscle Relaxant',
                'description' => 'For muscle spasms',
                'price' => 26.99,
                'stock_quantity' => 45,
                'manufacturer' => 'MuscleCare',
                'expiry_date' => '2025-10-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Pravastatin',
                'generic_name' => 'Pravastatin Sodium',
                'category' => 'Cholesterol',
                'description' => 'For high cholesterol',
                'price' => 34.99,
                'stock_quantity' => 40,
                'manufacturer' => 'HeartCare',
                'expiry_date' => '2025-11-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Trazodone',
                'generic_name' => 'Trazodone HCl',
                'category' => 'Antidepressant',
                'description' => 'For depression and insomnia',
                'price' => 29.99,
                'stock_quantity' => 45,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-12-20',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Dicyclomine',
                'generic_name' => 'Dicyclomine HCl',
                'category' => 'Antispasmodic',
                'description' => 'For IBS and stomach cramps',
                'price' => 24.99,
                'stock_quantity' => 50,
                'manufacturer' => 'GastroHealth',
                'expiry_date' => '2025-06-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Buspirone',
                'generic_name' => 'Buspirone HCl',
                'category' => 'Anti-anxiety',
                'description' => 'For anxiety disorders',
                'price' => 31.99,
                'stock_quantity' => 40,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-07-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Propranolol',
                'generic_name' => 'Propranolol HCl',
                'category' => 'Beta Blocker',
                'description' => 'For high blood pressure and migraines',
                'price' => 27.99,
                'stock_quantity' => 45,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-08-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Naproxen',
                'generic_name' => 'Naproxen Sodium',
                'category' => 'Pain Reliever',
                'description' => 'For pain and inflammation',
                'price' => 14.99,
                'stock_quantity' => 80,
                'manufacturer' => 'PainFree',
                'expiry_date' => '2025-09-25',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Famotidine',
                'generic_name' => 'Famotidine',
                'category' => 'Antacid',
                'description' => 'For heartburn and ulcers',
                'price' => 17.99,
                'stock_quantity' => 65,
                'manufacturer' => 'GastroHealth',
                'expiry_date' => '2025-10-25',
                'requires_prescription' => false,
                'status' => 'active'
            ],
            [
                'name' => 'Diazepam',
                'generic_name' => 'Diazepam',
                'category' => 'Anti-anxiety',
                'description' => 'For anxiety and muscle spasms',
                'price' => 41.99,
                'stock_quantity' => 30,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-11-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Prednisone',
                'generic_name' => 'Prednisone',
                'category' => 'Corticosteroid',
                'description' => 'For inflammation and allergies',
                'price' => 19.99,
                'stock_quantity' => 55,
                'manufacturer' => 'ImmunoMed',
                'expiry_date' => '2025-12-25',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Alprazolam',
                'generic_name' => 'Alprazolam',
                'category' => 'Anti-anxiety',
                'description' => 'For anxiety and panic disorders',
                'price' => 43.99,
                'stock_quantity' => 25,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-06-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Metronidazole',
                'generic_name' => 'Metronidazole',
                'category' => 'Antibiotic',
                'description' => 'For bacterial infections',
                'price' => 22.99,
                'stock_quantity' => 45,
                'manufacturer' => 'Medical Labs',
                'expiry_date' => '2025-07-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Simvastatin',
                'generic_name' => 'Simvastatin',
                'category' => 'Cholesterol',
                'description' => 'For high cholesterol',
                'price' => 32.99,
                'stock_quantity' => 50,
                'manufacturer' => 'HeartCare',
                'expiry_date' => '2025-08-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Methylphenidate',
                'generic_name' => 'Methylphenidate HCl',
                'category' => 'Stimulant',
                'description' => 'For ADHD',
                'price' => 54.99,
                'stock_quantity' => 30,
                'manufacturer' => 'NeuroCare',
                'expiry_date' => '2025-09-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Ondansetron',
                'generic_name' => 'Ondansetron HCl',
                'category' => 'Antiemetic',
                'description' => 'For nausea and vomiting',
                'price' => 46.99,
                'stock_quantity' => 40,
                'manufacturer' => 'GastroHealth',
                'expiry_date' => '2025-10-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Clindamycin',
                'generic_name' => 'Clindamycin HCl',
                'category' => 'Antibiotic',
                'description' => 'For serious bacterial infections',
                'price' => 38.99,
                'stock_quantity' => 35,
                'manufacturer' => 'Medical Labs',
                'expiry_date' => '2025-11-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Promethazine',
                'generic_name' => 'Promethazine HCl',
                'category' => 'Antihistamine',
                'description' => 'For allergies and motion sickness',
                'price' => 25.99,
                'stock_quantity' => 45,
                'manufacturer' => 'AllergyMed',
                'expiry_date' => '2025-12-30',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Oxycodone',
                'generic_name' => 'Oxycodone HCl',
                'category' => 'Pain Reliever',
                'description' => 'For severe pain',
                'price' => 89.99,
                'stock_quantity' => 20,
                'manufacturer' => 'PainFree',
                'expiry_date' => '2025-06-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Hydrochlorothiazide',
                'generic_name' => 'Hydrochlorothiazide',
                'category' => 'Diuretic',
                'description' => 'For high blood pressure and fluid retention',
                'price' => 23.99,
                'stock_quantity' => 55,
                'manufacturer' => 'CardioMed',
                'expiry_date' => '2025-07-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Azithromycin',
                'generic_name' => 'Azithromycin',
                'category' => 'Antibiotic',
                'description' => 'For bacterial infections',
                'price' => 35.99,
                'stock_quantity' => 40,
                'manufacturer' => 'Medical Labs',
                'expiry_date' => '2025-08-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Risperidone',
                'generic_name' => 'Risperidone',
                'category' => 'Antipsychotic',
                'description' => 'For schizophrenia and bipolar disorder',
                'price' => 67.99,
                'stock_quantity' => 25,
                'manufacturer' => 'MentalHealth',
                'expiry_date' => '2025-09-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Baclofen',
                'generic_name' => 'Baclofen',
                'category' => 'Muscle Relaxant',
                'description' => 'For muscle spasms and pain',
                'price' => 29.99,
                'stock_quantity' => 45,
                'manufacturer' => 'MuscleCare',
                'expiry_date' => '2025-10-15',
                'requires_prescription' => true,
                'status' => 'active'
            ],
            [
                'name' => 'Doxycycline',
                'generic_name' => 'Doxycycline Hyclate',
                'category' => 'Antibiotic',
                'description' => 'For bacterial infections and acne',
                'price' => 32.99,
                'stock_quantity' => 50,
                'manufacturer' => 'Medical Labs',
                'expiry_date' => '2025-11-15',
                'requires_prescription' => true,
                'status' => 'active'
            ]
        ];

        foreach ($medicines as $medicine) {
            Pharmacy::create($medicine);
        }
    }
}